name: GitHub Actions 

on:
   push:
      branches: [ malak ]

jobs:

   build-on-ubuntu:
     runs-on: ubuntu-latest

     steps:
       - name: Step 1 - Checkout malak branch from GitHub
         uses: actions/checkout@v2

       - name: Step 2 - Set up JDK 1.11
         uses: actions/setup-java@v1
         with:
           java-version: 1.11

       - name: Step 3 - Build Maven Project
         run: mvn  --batch-mode clean -DskipTests

       - name: Step 4 - run test cases
         run: mvn  --batch-mode -Dmaven.test.failure.ignore=true test
      

           

         
